import instructions from '../instructions'

export default {
    displayName: 'Maze 113',
    description: 'Just another TrivialMaze Maze',
    unlocksLevels: ['0114'],
    rows: 7,
    cols: 7,
    unlocksInstructions: [],
    levelTiles: [
        { x: 5, y: 1, ...instructions['STRT'] },
        { x: 1, y: 2, ...instructions['BLCK'] },
        { x: 2, y: 2, ...instructions['BLCK'] },
        { x: 3, y: 2, ...instructions['BLCK'] },
        { x: 4, y: 2, ...instructions['BLCK'] },
        { x: 5, y: 2, ...instructions['BLCK'] },
        { x: 6, y: 2, ...instructions['BLCK'] },
        { x: 6, y: 3, ...instructions['BLCK'] },
        { x: 2, y: 4, ...instructions['BLCK'] },
        { x: 3, y: 4, ...instructions['BLCK'] },
        { x: 4, y: 4, ...instructions['BLCK'] },
        { x: 6, y: 4, ...instructions['BLCK'] },
        { x: 1, y: 5, ...instructions['FINI'] },
        { x: 2, y: 5, ...instructions['BLCK'] },
        { x: 6, y: 5, ...instructions['BLCK'] },
        { x: 2, y: 6, ...instructions['BLCK'] },
        { x: 3, y: 6, ...instructions['BLCK'] },
        { x: 4, y: 6, ...instructions['BLCK'] },
        { x: 5, y: 6, ...instructions['BLCK'] },
        { x: 6, y: 6, ...instructions['BLCK'] },
    ],
}
