import instructions from '../instructions'

export default {
    displayName: 'Maze 125',
    description: 'Just another Prims Maze',
    unlocksLevels: ['0126'],
    rows: 9,
    cols: 9,
    unlocksInstructions: [],
    levelTiles: [
        { x: 4, y: 1, ...instructions['BLCK'] },
        { x: 6, y: 1, ...instructions['BLCK'] },
        { x: 8, y: 1, ...instructions['BLCK'] },
        { x: 1, y: 2, ...instructions['BLCK'] },
        { x: 2, y: 2, ...instructions['BLCK'] },
        { x: 4, y: 2, ...instructions['BLCK'] },
        { x: 6, y: 2, ...instructions['BLCK'] },
        { x: 8, y: 2, ...instructions['BLCK'] },
        { x: 1, y: 4, ...instructions['BLCK'] },
        { x: 2, y: 4, ...instructions['BLCK'] },
        { x: 4, y: 4, ...instructions['BLCK'] },
        { x: 6, y: 4, ...instructions['BLCK'] },
        { x: 8, y: 4, ...instructions['BLCK'] },
        { x: 4, y: 5, ...instructions['BLCK'] },
        { x: 6, y: 5, ...instructions['BLCK'] },
        { x: 8, y: 5, ...instructions['BLCK'] },
        { x: 1, y: 6, ...instructions['BLCK'] },
        { x: 2, y: 6, ...instructions['BLCK'] },
        { x: 4, y: 6, ...instructions['BLCK'] },
        { x: 5, y: 6, ...instructions['BLCK'] },
        { x: 6, y: 6, ...instructions['BLCK'] },
        { x: 7, y: 6, ...instructions['BLCK'] },
        { x: 8, y: 6, ...instructions['BLCK'] },
        { x: 2, y: 7, ...instructions['BLCK'] },
        { x: 6, y: 7, ...instructions['BLCK'] },
        { x: 7, y: 7, ...instructions['FINI'] },
        { x: 8, y: 7, ...instructions['BLCK'] },
        { x: 2, y: 8, ...instructions['BLCK'] },
        { x: 4, y: 8, ...instructions['BLCK'] },
        { x: 5, y: 8, ...instructions['BLCK'] },
        { x: 6, y: 8, ...instructions['BLCK'] },
        { x: 8, y: 8, ...instructions['BLCK'] },
        { x: 9, y: 8, ...instructions['BLCK'] },
        { x: 1, y: 9, ...instructions['STRT'] },
    ],
}
