import instructions from '../instructions'

export default {
    displayName: 'Maze 153',
    description: 'Just another Prims Maze',
    unlocksLevels: ['0154'],
    rows: 13,
    cols: 13,
    unlocksInstructions: [],
    levelTiles: [
        { x: 2, y: 1, ...instructions['BLCK'] },
        { x: 8, y: 1, ...instructions['BLCK'] },
        { x: 2, y: 2, ...instructions['BLCK'] },
        { x: 3, y: 2, ...instructions['BLCK'] },
        { x: 4, y: 2, ...instructions['BLCK'] },
        { x: 6, y: 2, ...instructions['BLCK'] },
        { x: 7, y: 2, ...instructions['BLCK'] },
        { x: 8, y: 2, ...instructions['BLCK'] },
        { x: 10, y: 2, ...instructions['BLCK'] },
        { x: 12, y: 2, ...instructions['BLCK'] },
        { x: 2, y: 3, ...instructions['BLCK'] },
        { x: 6, y: 3, ...instructions['BLCK'] },
        { x: 10, y: 3, ...instructions['BLCK'] },
        { x: 12, y: 3, ...instructions['BLCK'] },
        { x: 2, y: 4, ...instructions['BLCK'] },
        { x: 3, y: 4, ...instructions['BLCK'] },
        { x: 4, y: 4, ...instructions['BLCK'] },
        { x: 6, y: 4, ...instructions['BLCK'] },
        { x: 7, y: 4, ...instructions['BLCK'] },
        { x: 8, y: 4, ...instructions['BLCK'] },
        { x: 10, y: 4, ...instructions['BLCK'] },
        { x: 11, y: 4, ...instructions['BLCK'] },
        { x: 12, y: 4, ...instructions['BLCK'] },
        { x: 13, y: 4, ...instructions['BLCK'] },
        { x: 4, y: 5, ...instructions['BLCK'] },
        { x: 8, y: 5, ...instructions['BLCK'] },
        { x: 1, y: 6, ...instructions['BLCK'] },
        { x: 2, y: 6, ...instructions['BLCK'] },
        { x: 4, y: 6, ...instructions['BLCK'] },
        { x: 6, y: 6, ...instructions['BLCK'] },
        { x: 7, y: 6, ...instructions['BLCK'] },
        { x: 8, y: 6, ...instructions['BLCK'] },
        { x: 10, y: 6, ...instructions['BLCK'] },
        { x: 11, y: 6, ...instructions['BLCK'] },
        { x: 12, y: 6, ...instructions['BLCK'] },
        { x: 13, y: 6, ...instructions['BLCK'] },
        { x: 4, y: 7, ...instructions['BLCK'] },
        { x: 12, y: 7, ...instructions['BLCK'] },
        { x: 1, y: 8, ...instructions['BLCK'] },
        { x: 2, y: 8, ...instructions['BLCK'] },
        { x: 4, y: 8, ...instructions['BLCK'] },
        { x: 6, y: 8, ...instructions['BLCK'] },
        { x: 7, y: 8, ...instructions['BLCK'] },
        { x: 8, y: 8, ...instructions['BLCK'] },
        { x: 9, y: 8, ...instructions['BLCK'] },
        { x: 10, y: 8, ...instructions['BLCK'] },
        { x: 11, y: 8, ...instructions['BLCK'] },
        { x: 12, y: 8, ...instructions['BLCK'] },
        { x: 3, y: 9, ...instructions['STRT'] },
        { x: 6, y: 9, ...instructions['BLCK'] },
        { x: 10, y: 9, ...instructions['BLCK'] },
        { x: 11, y: 9, ...instructions['FINI'] },
        { x: 1, y: 10, ...instructions['BLCK'] },
        { x: 2, y: 10, ...instructions['BLCK'] },
        { x: 4, y: 10, ...instructions['BLCK'] },
        { x: 5, y: 10, ...instructions['BLCK'] },
        { x: 6, y: 10, ...instructions['BLCK'] },
        { x: 7, y: 10, ...instructions['BLCK'] },
        { x: 8, y: 10, ...instructions['BLCK'] },
        { x: 10, y: 10, ...instructions['BLCK'] },
        { x: 12, y: 10, ...instructions['BLCK'] },
        { x: 13, y: 10, ...instructions['BLCK'] },
        { x: 4, y: 11, ...instructions['BLCK'] },
        { x: 2, y: 12, ...instructions['BLCK'] },
        { x: 4, y: 12, ...instructions['BLCK'] },
        { x: 6, y: 12, ...instructions['BLCK'] },
        { x: 7, y: 12, ...instructions['BLCK'] },
        { x: 8, y: 12, ...instructions['BLCK'] },
        { x: 10, y: 12, ...instructions['BLCK'] },
        { x: 12, y: 12, ...instructions['BLCK'] },
        { x: 13, y: 12, ...instructions['BLCK'] },
        { x: 2, y: 13, ...instructions['BLCK'] },
        { x: 8, y: 13, ...instructions['BLCK'] },
        { x: 10, y: 13, ...instructions['BLCK'] },
    ],
}
